"""
This type stub file was generated by pyright.
"""

import inspect
from collections.abc import Callable, Mapping, Sequence
from contextlib import AsyncExitStack
from dataclasses import dataclass
from typing import Any, Literal
from fastapi import params
from fastapi._compat import ModelField
from fastapi.dependencies.models import Dependant, _UsesScopesCache
from fastapi.types import DependencyCacheKey
from starlette.background import BackgroundTasks as StarletteBackgroundTasks
from starlette.datastructures import FormData, Headers, QueryParams
from starlette.requests import Request
from starlette.responses import Response
from starlette.websockets import WebSocket

multipart_not_installed_error = ...
multipart_incorrect_install_error = ...
def ensure_multipart_is_installed() -> None:
    ...

def get_parameterless_sub_dependant(*, depends: params.Depends, path: str) -> Dependant:
    ...

def get_flat_params(dependant: Dependant) -> list[ModelField]:
    ...

def get_typed_signature(call: Callable[..., Any]) -> inspect.Signature:
    ...

def get_typed_annotation(annotation: Any, globalns: dict[str, Any]) -> Any:
    ...

def get_typed_return_annotation(call: Callable[..., Any]) -> Any:
    ...

_STREAM_ORIGINS = ...
def get_stream_item_type(annotation: Any) -> Any | None:
    ...

def get_dependant(*, path: str, call: Callable[..., Any], name: str | None = ..., own_oauth_scopes: list[str] | None = ..., parent_oauth_scopes: list[str] | None = ..., use_cache: bool = ..., scope: Literal["function", "request"] | None = ...) -> Dependant:
    ...

def add_non_field_param_to_dependency(*, param_name: str, type_annotation: Any, dependant: Dependant) -> bool | None:
    ...

@dataclass
class ParamDetails:
    type_annotation: Any
    depends: params.Depends | None
    field: ModelField | None
    ...


def analyze_param(*, param_name: str, annotation: Any, value: Any, is_path_param: bool) -> ParamDetails:
    ...

def add_param_to_fields(*, field: ModelField, dependant: Dependant) -> None:
    ...

@dataclass
class SolvedDependency:
    values: dict[str, Any]
    errors: list[Any]
    background_tasks: StarletteBackgroundTasks | None
    response: Response
    dependency_cache: dict[DependencyCacheKey, Any]
    ...


async def solve_dependencies(*, request: Request | WebSocket, dependant: Dependant, body: dict[str, Any] | FormData | bytes | None = ..., background_tasks: StarletteBackgroundTasks | None = ..., response: Response | None = ..., dependency_overrides_provider: Any | None = ..., dependency_cache: dict[DependencyCacheKey, Any] | None = ..., async_exit_stack: AsyncExitStack, embed_body_fields: bool, _uses_scopes_cache: _UsesScopesCache | None = ...) -> SolvedDependency:
    ...

def request_params_to_args(fields: Sequence[ModelField], received_params: Mapping[str, Any] | QueryParams | Headers) -> tuple[dict[str, Any], list[Any]]:
    ...

def is_union_of_base_models(field_type: Any) -> bool:
    """Check if field type is a Union where all members are BaseModel subclasses."""
    ...

async def request_body_to_args(body_fields: list[ModelField], received_body: dict[str, Any] | FormData | bytes | None, embed_body_fields: bool) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    ...

def get_validation_alias(field: ModelField) -> str:
    ...

