"""
This type stub file was generated by pyright.
"""

from starlette import status as status
from .applications import FastAPI as FastAPI
from .background import BackgroundTasks as BackgroundTasks
from .datastructures import UploadFile as UploadFile
from .exceptions import HTTPException as HTTPException, WebSocketException as WebSocketException
from .param_functions import Body as Body, Cookie as Cookie, Depends as Depends, File as File, Form as Form, Header as Header, Path as Path, Query as Query, Security as Security
from .requests import Request as Request
from .responses import Response as Response
from .routing import APIRouter as APIRouter
from .websockets import WebSocket as WebSocket, WebSocketDisconnect as WebSocketDisconnect

"""FastAPI framework, high performance, easy to learn, fast to code, ready for production"""
__version__ = ...
