"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncGenerator
from contextlib import AbstractContextManager, asynccontextmanager as asynccontextmanager
from typing import TypeVar

_T = TypeVar("_T")
@asynccontextmanager
async def contextmanager_in_threadpool(cm: AbstractContextManager[_T]) -> AsyncGenerator[_T, None]:
    ...

