"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Mapping
from typing import Annotated, Any, BinaryIO, TypeVar
from annotated_doc import Doc
from pydantic import GetJsonSchemaHandler
from starlette.datastructures import Headers as Headers, UploadFile as StarletteUploadFile

class UploadFile(StarletteUploadFile):
    """
    A file uploaded in a request.

    Define it as a *path operation function* (or dependency) parameter.

    If you are using a regular `def` function, you can use the `upload_file.file`
    attribute to access the raw standard Python file (blocking, not async), useful and
    needed for non-async code.

    Read more about it in the
    [FastAPI docs for Request Files](https://fastapi.tiangolo.com/tutorial/request-files/).

    ## Example

    ```python
    from typing import Annotated

    from fastapi import FastAPI, File, UploadFile

    app = FastAPI()


    @app.post("/files/")
    async def create_file(file: Annotated[bytes, File()]):
        return {"file_size": len(file)}


    @app.post("/uploadfile/")
    async def create_upload_file(file: UploadFile):
        return {"filename": file.filename}
    ```
    """
    file: Annotated[BinaryIO, Doc("The standard Python file object (non-async)."),]
    filename: Annotated[str | None, Doc("The original file name.")]
    size: Annotated[int | None, Doc("The size of the file in bytes.")]
    headers: Annotated[Headers, Doc("The headers of the request.")]
    content_type: Annotated[str | None, Doc("The content type of the request, from the headers.")]
    async def write(self, data: Annotated[bytes, Doc("""
                The bytes to write to the file.
                """),]) -> None:
        """
        Write some bytes to the file.

        You normally wouldn't use this from a file you read in a request.

        To be awaitable, compatible with async, this is run in threadpool.
        """
        ...
    
    async def read(self, size: Annotated[int, Doc("""
                The number of bytes to read from the file.
                """),] = ...) -> bytes:
        """
        Read some bytes from the file.

        To be awaitable, compatible with async, this is run in threadpool.
        """
        ...
    
    async def seek(self, offset: Annotated[int, Doc("""
                The position in bytes to seek to in the file.
                """),]) -> None:
        """
        Move to a position in the file.

        Any next read or write will be done from that position.

        To be awaitable, compatible with async, this is run in threadpool.
        """
        ...
    
    async def close(self) -> None:
        """
        Close the file.

        To be awaitable, compatible with async, this is run in threadpool.
        """
        ...
    
    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: Mapping[str, Any], handler: GetJsonSchemaHandler) -> dict[str, Any]:
        ...
    
    @classmethod
    def __get_pydantic_core_schema__(cls, source: type[Any], handler: Callable[[Any], Mapping[str, Any]]) -> Mapping[str, Any]:
        ...
    


class DefaultPlaceholder:
    """
    You shouldn't use this class directly.

    It's used internally to recognize when a default value has been overwritten, even
    if the overridden default value was truthy.
    """
    def __init__(self, value: Any) -> None:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __eq__(self, o: object) -> bool:
        ...
    


DefaultType = TypeVar("DefaultType")
def Default(value: DefaultType) -> DefaultType:
    """
    You shouldn't use this function directly.

    It's used internally to recognize when a default value has been overwritten, even
    if the overridden default value was truthy.
    """
    ...

_Unset = ...
