"""
This type stub file was generated by pyright.
"""

import datetime
from collections.abc import Callable
from decimal import Decimal
from typing import Annotated, Any
from annotated_doc import Doc
from fastapi.types import IncEx

def isoformat(o: datetime.date | datetime.time) -> str:
    ...

def decimal_encoder(dec_value: Decimal) -> int | float:
    """
    Encodes a Decimal as int if there's no exponent, otherwise float

    This is useful when we use ConstrainedDecimal to represent Numeric(x,0)
    where an integer (but not int typed) is used. Encoding this as a float
    results in failed round-tripping between encode and parse.
    Our Id type is a prime example of this.

    >>> decimal_encoder(Decimal("1.0"))
    1.0

    >>> decimal_encoder(Decimal("1"))
    1

    >>> decimal_encoder(Decimal("NaN"))
    nan
    """
    ...

ENCODERS_BY_TYPE: dict[type[Any], Callable[[Any], Any]] = ...
def generate_encoders_by_class_tuples(type_encoder_map: dict[Any, Callable[[Any], Any]]) -> dict[Callable[[Any], Any], tuple[Any, ...]]:
    ...

encoders_by_class_tuples = ...
def jsonable_encoder(obj: Annotated[Any, Doc("""
            The input object to convert to JSON.
            """),], include: Annotated[IncEx | None, Doc("""
            Pydantic's `include` parameter, passed to Pydantic models to set the
            fields to include.
            """),] = ..., exclude: Annotated[IncEx | None, Doc("""
            Pydantic's `exclude` parameter, passed to Pydantic models to set the
            fields to exclude.
            """),] = ..., by_alias: Annotated[bool, Doc("""
            Pydantic's `by_alias` parameter, passed to Pydantic models to define if
            the output should use the alias names (when provided) or the Python
            attribute names. In an API, if you set an alias, it's probably because you
            want to use it in the result, so you probably want to leave this set to
            `True`.
            """),] = ..., exclude_unset: Annotated[bool, Doc("""
            Pydantic's `exclude_unset` parameter, passed to Pydantic models to define
            if it should exclude from the output the fields that were not explicitly
            set (and that only had their default values).
            """),] = ..., exclude_defaults: Annotated[bool, Doc("""
            Pydantic's `exclude_defaults` parameter, passed to Pydantic models to define
            if it should exclude from the output the fields that had the same default
            value, even when they were explicitly set.
            """),] = ..., exclude_none: Annotated[bool, Doc("""
            Pydantic's `exclude_none` parameter, passed to Pydantic models to define
            if it should exclude from the output any fields that have a `None` value.
            """),] = ..., custom_encoder: Annotated[dict[Any, Callable[[Any], Any]] | None, Doc("""
            Pydantic's `custom_encoder` parameter, passed to Pydantic models to define
            a custom encoder.
            """),] = ..., sqlalchemy_safe: Annotated[bool, Doc("""
            Exclude from the output any fields that start with the name `_sa`.

            This is mainly a hack for compatibility with SQLAlchemy objects, they
            store internal SQLAlchemy-specific state in attributes named with `_sa`,
            and those objects can't (and shouldn't be) serialized to JSON.
            """),] = ...) -> Any:
    """
    Convert any object to something that can be encoded in JSON.

    This is used internally by FastAPI to make sure anything you return can be
    encoded as JSON before it is sent to the client.

    You can also use it yourself, for example to convert objects before saving them
    in a database that supports only JSON.

    Read more about it in the
    [FastAPI docs for JSON Compatible Encoder](https://fastapi.tiangolo.com/tutorial/encoder/).
    """
    ...

