"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping, Sequence
from typing import Any, TypedDict
from pydantic import BaseModel
from starlette.exceptions import HTTPException as StarletteHTTPException, WebSocketException as StarletteWebSocketException

class EndpointContext(TypedDict, total=False):
    function: str
    path: str
    file: str
    line: int
    ...


class HTTPException(StarletteHTTPException):
    """
    An HTTP exception you can raise in your own code to show errors to the client.

    This is for client errors, invalid authentication, invalid data, etc. Not for server
    errors in your code.

    Read more about it in the
    [FastAPI docs for Handling Errors](https://fastapi.tiangolo.com/tutorial/handling-errors/).

    ## Example

    ```python
    from fastapi import FastAPI, HTTPException

    app = FastAPI()

    items = {"foo": "The Foo Wrestlers"}


    @app.get("/items/{item_id}")
    async def read_item(item_id: str):
        if item_id not in items:
            raise HTTPException(status_code=404, detail="Item not found")
        return {"item": items[item_id]}
    ```
    """
    def __init__(self, status_code: int, detail: Any = ..., headers: Mapping[str, str] | None = ...) -> None:
        """
        ## Parameters

        ### `status_code`

        HTTP status code to send to the client.

        Read more about it in the
        [FastAPI docs for Handling Errors](https://fastapi.tiangolo.com/tutorial/handling-errors/#use-httpexception)

        ### `detail`

        Any data to be sent to the client in the `detail` key of the JSON
        response.

        Read more about it in the
        [FastAPI docs for Handling Errors](https://fastapi.tiangolo.com/tutorial/handling-errors/#use-httpexception)

        ### `headers`

        Any headers to send to the client in the response.

        Read more about it in the
        [FastAPI docs for Handling Errors](https://fastapi.tiangolo.com/tutorial/handling-errors/#add-custom-headers)
        """
        ...
    


class WebSocketException(StarletteWebSocketException):
    """
    A WebSocket exception you can raise in your own code to show errors to the client.

    This is for client errors, invalid authentication, invalid data, etc. Not for server
    errors in your code.

    Read more about it in the
    [FastAPI docs for WebSockets](https://fastapi.tiangolo.com/advanced/websockets/).

    ## Example

    ```python
    from typing import Annotated

    from fastapi import (
        Cookie,
        FastAPI,
        WebSocket,
        WebSocketException,
        status,
    )

    app = FastAPI()

    @app.websocket("/items/{item_id}/ws")
    async def websocket_endpoint(
        *,
        websocket: WebSocket,
        session: Annotated[str | None, Cookie()] = None,
        item_id: str,
    ):
        if session is None:
            raise WebSocketException(code=status.WS_1008_POLICY_VIOLATION)
        await websocket.accept()
        while True:
            data = await websocket.receive_text()
            await websocket.send_text(f"Session cookie is: {session}")
            await websocket.send_text(f"Message text was: {data}, for item ID: {item_id}")
    ```
    """
    def __init__(self, code: int, reason: str | None = ...) -> None:
        """
        ## Parameters

        ### `code`

        A closing code from the
        [valid codes defined in the specification](https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.1).

        ### `reason`

        The reason to close the WebSocket connection.

        It is UTF-8-encoded data. The interpretation of the reason is up to the
        application, it is not specified by the WebSocket specification.

        It could contain text that could be human-readable or interpretable
        by the client code, etc.
        """
        ...
    


RequestErrorModel: type[BaseModel] = ...
WebSocketErrorModel: type[BaseModel] = ...
class FastAPIError(RuntimeError):
    """
    A generic, FastAPI-specific error.
    """
    ...


class DependencyScopeError(FastAPIError):
    """
    A dependency declared that it depends on another dependency with an invalid
    (narrower) scope.
    """
    ...


class ValidationException(Exception):
    def __init__(self, errors: Sequence[Any], *, endpoint_ctx: EndpointContext | None = ...) -> None:
        ...
    
    def errors(self) -> Sequence[Any]:
        ...
    
    def __str__(self) -> str:
        ...
    


class RequestValidationError(ValidationException):
    def __init__(self, errors: Sequence[Any], *, body: Any = ..., endpoint_ctx: EndpointContext | None = ...) -> None:
        ...
    


class WebSocketRequestValidationError(ValidationException):
    def __init__(self, errors: Sequence[Any], *, endpoint_ctx: EndpointContext | None = ...) -> None:
        ...
    


class ResponseValidationError(ValidationException):
    def __init__(self, errors: Sequence[Any], *, body: Any = ..., endpoint_ctx: EndpointContext | None = ...) -> None:
        ...
    


class PydanticV1NotSupportedError(FastAPIError):
    """
    A pydantic.v1 model is used, which is no longer supported.
    """
    ...


class FastAPIDeprecationWarning(UserWarning):
    """
    A custom deprecation warning as DeprecationWarning is ignored
    Ref: https://sethmlarson.dev/deprecations-via-warnings-dont-work-for-python-libraries
    """
    ...


