"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from dataclasses import dataclass
from enum import Enum
from typing import Annotated, Any, Literal
from fastapi.openapi.models import Example
from pydantic import AliasChoices, AliasPath
from pydantic.fields import FieldInfo
from typing_extensions import deprecated

class ParamTypes(Enum):
    query = ...
    header = ...
    path = ...
    cookie = ...


class Param(FieldInfo):
    in_: ParamTypes
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class Path(Param):
    in_ = ...
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    


class Query(Param):
    in_ = ...
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    


class Header(Param):
    in_ = ...
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., convert_underscores: bool = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    


class Cookie(Param):
    in_ = ...
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    


class Body(FieldInfo):
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., embed: bool | None = ..., media_type: str = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class Form(Body):
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., media_type: str = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    


class File(Form):
    def __init__(self, default: Any = ..., *, default_factory: Callable[[], Any] | None = ..., annotation: Any | None = ..., media_type: str = ..., alias: str | None = ..., alias_priority: int | None = ..., validation_alias: str | AliasPath | AliasChoices | None = ..., serialization_alias: str | None = ..., title: str | None = ..., description: str | None = ..., gt: float | None = ..., ge: float | None = ..., lt: float | None = ..., le: float | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., regex: Annotated[str | None, deprecated("Deprecated in FastAPI 0.100.0 and Pydantic v2, use `pattern` instead."),] = ..., discriminator: str | None = ..., strict: bool | None = ..., multiple_of: float | None = ..., allow_inf_nan: bool | None = ..., max_digits: int | None = ..., decimal_places: int | None = ..., examples: list[Any] | None = ..., example: Annotated[Any | None, deprecated("Deprecated in OpenAPI 3.1.0 that now uses JSON Schema 2020-12, " "although still supported. Use examples instead."),] = ..., openapi_examples: dict[str, Example] | None = ..., deprecated: deprecated | str | bool | None = ..., include_in_schema: bool = ..., json_schema_extra: dict[str, Any] | None = ..., **extra: Any) -> None:
        ...
    


@dataclass(frozen=True)
class Depends:
    dependency: Callable[..., Any] | None = ...
    use_cache: bool = ...
    scope: Literal["function", "request"] | None = ...


@dataclass(frozen=True)
class Security(Depends):
    scopes: Sequence[str] | None = ...


