"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from enum import Enum
from typing import Any, TypeVar
from pydantic import BaseModel

DecoratedCallable = TypeVar("DecoratedCallable", bound=Callable[..., Any])
UnionType = ...
ModelNameMap = dict[type[BaseModel] | type[Enum], str]
DependencyCacheKey = tuple[Callable[..., Any] | None, tuple[str, ...], str]
