"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING
from fastapi._compat import ModelField
from fastapi.datastructures import DefaultPlaceholder, DefaultType
from pydantic.fields import FieldInfo
from .routing import APIRoute

if TYPE_CHECKING:
    ...
def is_body_allowed_for_status_code(status_code: int | str | None) -> bool:
    ...

def get_path_param_names(path: str) -> set[str]:
    ...

_invalid_args_message = ...
def create_model_field(name: str, type_: Any, default: Any | None = ..., field_info: FieldInfo | None = ..., alias: str | None = ..., mode: Literal["validation", "serialization"] = ...) -> ModelField:
    ...

def generate_operation_id_for_path(*, name: str, path: str, method: str) -> str:
    ...

def generate_unique_id(route: APIRoute) -> str:
    ...

def deep_dict_update(main_dict: dict[Any, Any], update_dict: dict[Any, Any]) -> None:
    ...

def get_value_or_default(first_item: DefaultPlaceholder | DefaultType, *extra_items: DefaultPlaceholder | DefaultType) -> DefaultPlaceholder | DefaultType:
    """
    Pass items or `DefaultPlaceholder`s by descending priority.

    The first one to _not_ be a `DefaultPlaceholder` will be returned.

    Otherwise, the first item (a `DefaultPlaceholder`) will be returned.
    """
    ...

