"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum
from functools import lru_cache
from typing import Any, Literal
from fastapi.types import IncEx, ModelNameMap
from pydantic import BaseModel, ConfigDict
from pydantic.fields import FieldInfo as FieldInfo
from pydantic.json_schema import GenerateJsonSchema as _GenerateJsonSchema, JsonSchemaValue as JsonSchemaValue
from pydantic_core import CoreSchema as CoreSchema

RequiredParam = ...
Undefined = ...
def evaluate_forwardref(value: Any, globalns: dict[str, Any] | None = ..., localns: dict[str, Any] | None = ...) -> Any:
    ...

class GenerateJsonSchema(_GenerateJsonSchema):
    def bytes_schema(self, schema: CoreSchema) -> JsonSchemaValue:
        ...
    


_Attrs = ...
def asdict(field_info: FieldInfo) -> dict[str, Any]:
    ...

@dataclass
class ModelField:
    field_info: FieldInfo
    name: str
    mode: Literal["validation", "serialization"] = ...
    config: ConfigDict | None = ...
    @property
    def alias(self) -> str:
        ...
    
    @property
    def validation_alias(self) -> str | None:
        ...
    
    @property
    def serialization_alias(self) -> str | None:
        ...
    
    @property
    def default(self) -> Any:
        ...
    
    def __post_init__(self) -> None:
        ...
    
    def get_default(self) -> Any:
        ...
    
    def validate(self, value: Any, values: dict[str, Any] = ..., *, loc: tuple[int | str, ...] = ...) -> tuple[Any, list[dict[str, Any]]]:
        ...
    
    def serialize(self, value: Any, *, mode: Literal["json", "python"] = ..., include: IncEx | None = ..., exclude: IncEx | None = ..., by_alias: bool = ..., exclude_unset: bool = ..., exclude_defaults: bool = ..., exclude_none: bool = ...) -> Any:
        ...
    
    def serialize_json(self, value: Any, *, include: IncEx | None = ..., exclude: IncEx | None = ..., by_alias: bool = ..., exclude_unset: bool = ..., exclude_defaults: bool = ..., exclude_none: bool = ...) -> bytes:
        ...
    
    def __hash__(self) -> int:
        ...
    


def get_schema_from_model_field(*, field: ModelField, model_name_map: ModelNameMap, field_mapping: dict[tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue], separate_input_output_schemas: bool = ...) -> dict[str, Any]:
    ...

def get_definitions(*, fields: Sequence[ModelField], model_name_map: ModelNameMap, separate_input_output_schemas: bool = ...) -> tuple[dict[tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue], dict[str, dict[str, Any]],]:
    ...

def is_scalar_field(field: ModelField) -> bool:
    ...

def copy_field_info(*, field_info: FieldInfo, annotation: Any) -> FieldInfo:
    ...

def serialize_sequence_value(*, field: ModelField, value: Any) -> Sequence[Any]:
    ...

def get_missing_field_error(loc: tuple[int | str, ...]) -> dict[str, Any]:
    ...

def create_body_model(*, fields: Sequence[ModelField], model_name: str) -> type[BaseModel]:
    ...

def get_model_fields(model: type[BaseModel]) -> list[ModelField]:
    ...

@lru_cache
def get_cached_model_fields(model: type[BaseModel]) -> list[ModelField]:
    ...

TypeModelOrEnum = type["BaseModel"] | type[Enum]
TypeModelSet = set[TypeModelOrEnum]
def normalize_name(name: str) -> str:
    ...

def get_model_name_map(unique_models: TypeModelSet) -> dict[TypeModelOrEnum, str]:
    ...

def get_flat_models_from_model(model: type[BaseModel], known_models: TypeModelSet | None = ...) -> TypeModelSet:
    ...

def get_flat_models_from_annotation(annotation: Any, known_models: TypeModelSet) -> TypeModelSet:
    ...

def get_flat_models_from_field(field: ModelField, known_models: TypeModelSet) -> TypeModelSet:
    ...

def get_flat_models_from_fields(fields: Sequence[ModelField], known_models: TypeModelSet) -> TypeModelSet:
    ...

