"""
This type stub file was generated by pyright.
"""

from .api_key import APIKeyCookie as APIKeyCookie, APIKeyHeader as APIKeyHeader, APIKeyQuery as APIKeyQuery
from .http import HTTPAuthorizationCredentials as HTTPAuthorizationCredentials, HTTPBasic as HTTPBasic, HTTPBasicCredentials as HTTPBasicCredentials, HTTPBearer as HTTPBearer, HTTPDigest as HTTPDigest
from .oauth2 import OAuth2 as OAuth2, OAuth2AuthorizationCodeBearer as OAuth2AuthorizationCodeBearer, OAuth2PasswordBearer as OAuth2PasswordBearer, OAuth2PasswordRequestForm as OAuth2PasswordRequestForm, OAuth2PasswordRequestFormStrict as OAuth2PasswordRequestFormStrict, SecurityScopes as SecurityScopes
from .open_id_connect_url import OpenIdConnect as OpenIdConnect

