"""
This type stub file was generated by pyright.
"""

from typing import Annotated
from annotated_doc import Doc
from fastapi.exceptions import HTTPException
from fastapi.openapi.models import HTTPBase as HTTPBaseModel
from fastapi.security.base import SecurityBase
from pydantic import BaseModel
from starlette.requests import Request

class HTTPBasicCredentials(BaseModel):
    """
    The HTTP Basic credentials given as the result of using `HTTPBasic` in a
    dependency.

    Read more about it in the
    [FastAPI docs for HTTP Basic Auth](https://fastapi.tiangolo.com/advanced/security/http-basic-auth/).
    """
    username: Annotated[str, Doc("The HTTP Basic username.")]
    password: Annotated[str, Doc("The HTTP Basic password.")]
    ...


class HTTPAuthorizationCredentials(BaseModel):
    """
    The HTTP authorization credentials in the result of using `HTTPBearer` or
    `HTTPDigest` in a dependency.

    The HTTP authorization header value is split by the first space.

    The first part is the `scheme`, the second part is the `credentials`.

    For example, in an HTTP Bearer token scheme, the client will send a header
    like:

    ```
    Authorization: Bearer deadbeef12346
    ```

    In this case:

    * `scheme` will have the value `"Bearer"`
    * `credentials` will have the value `"deadbeef12346"`
    """
    scheme: Annotated[str, Doc("""
            The HTTP authorization scheme extracted from the header value.
            """),]
    credentials: Annotated[str, Doc("""
            The HTTP authorization credentials extracted from the header value.
            """),]
    ...


class HTTPBase(SecurityBase):
    model: HTTPBaseModel
    def __init__(self, *, scheme: str, scheme_name: str | None = ..., description: str | None = ..., auto_error: bool = ...) -> None:
        ...
    
    def make_authenticate_headers(self) -> dict[str, str]:
        ...
    
    def make_not_authenticated_error(self) -> HTTPException:
        ...
    
    async def __call__(self, request: Request) -> HTTPAuthorizationCredentials | None:
        ...
    


class HTTPBasic(HTTPBase):
    """
    HTTP Basic authentication.

    Ref: https://datatracker.ietf.org/doc/html/rfc7617

    ## Usage

    Create an instance object and use that object as the dependency in `Depends()`.

    The dependency result will be an `HTTPBasicCredentials` object containing the
    `username` and the `password`.

    Read more about it in the
    [FastAPI docs for HTTP Basic Auth](https://fastapi.tiangolo.com/advanced/security/http-basic-auth/).

    ## Example

    ```python
    from typing import Annotated

    from fastapi import Depends, FastAPI
    from fastapi.security import HTTPBasic, HTTPBasicCredentials

    app = FastAPI()

    security = HTTPBasic()


    @app.get("/users/me")
    def read_current_user(credentials: Annotated[HTTPBasicCredentials, Depends(security)]):
        return {"username": credentials.username, "password": credentials.password}
    ```
    """
    def __init__(self, *, scheme_name: Annotated[str | None, Doc("""
                Security scheme name.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., realm: Annotated[str | None, Doc("""
                HTTP Basic authentication realm.
                """),] = ..., description: Annotated[str | None, Doc("""
                Security scheme description.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., auto_error: Annotated[bool, Doc("""
                By default, if the HTTP Basic authentication is not provided (a
                header), `HTTPBasic` will automatically cancel the request and send the
                client an error.

                If `auto_error` is set to `False`, when the HTTP Basic authentication
                is not available, instead of erroring out, the dependency result will
                be `None`.

                This is useful when you want to have optional authentication.

                It is also useful when you want to have authentication that can be
                provided in one of multiple optional ways (for example, in HTTP Basic
                authentication or in an HTTP Bearer token).
                """),] = ...) -> None:
        ...
    
    def make_authenticate_headers(self) -> dict[str, str]:
        ...
    
    async def __call__(self, request: Request) -> HTTPBasicCredentials | None:
        ...
    


class HTTPBearer(HTTPBase):
    """
    HTTP Bearer token authentication.

    ## Usage

    Create an instance object and use that object as the dependency in `Depends()`.

    The dependency result will be an `HTTPAuthorizationCredentials` object containing
    the `scheme` and the `credentials`.

    ## Example

    ```python
    from typing import Annotated

    from fastapi import Depends, FastAPI
    from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

    app = FastAPI()

    security = HTTPBearer()


    @app.get("/users/me")
    def read_current_user(
        credentials: Annotated[HTTPAuthorizationCredentials, Depends(security)]
    ):
        return {"scheme": credentials.scheme, "credentials": credentials.credentials}
    ```
    """
    def __init__(self, *, bearerFormat: Annotated[str | None, Doc("Bearer token format.")] = ..., scheme_name: Annotated[str | None, Doc("""
                Security scheme name.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., description: Annotated[str | None, Doc("""
                Security scheme description.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., auto_error: Annotated[bool, Doc("""
                By default, if the HTTP Bearer token is not provided (in an
                `Authorization` header), `HTTPBearer` will automatically cancel the
                request and send the client an error.

                If `auto_error` is set to `False`, when the HTTP Bearer token
                is not available, instead of erroring out, the dependency result will
                be `None`.

                This is useful when you want to have optional authentication.

                It is also useful when you want to have authentication that can be
                provided in one of multiple optional ways (for example, in an HTTP
                Bearer token or in a cookie).
                """),] = ...) -> None:
        ...
    
    async def __call__(self, request: Request) -> HTTPAuthorizationCredentials | None:
        ...
    


class HTTPDigest(HTTPBase):
    """
    HTTP Digest authentication.

    **Warning**: this is only a stub to connect the components with OpenAPI in FastAPI,
    but it doesn't implement the full Digest scheme, you would need to subclass it
    and implement it in your code.

    Ref: https://datatracker.ietf.org/doc/html/rfc7616

    ## Usage

    Create an instance object and use that object as the dependency in `Depends()`.

    The dependency result will be an `HTTPAuthorizationCredentials` object containing
    the `scheme` and the `credentials`.

    ## Example

    ```python
    from typing import Annotated

    from fastapi import Depends, FastAPI
    from fastapi.security import HTTPAuthorizationCredentials, HTTPDigest

    app = FastAPI()

    security = HTTPDigest()


    @app.get("/users/me")
    def read_current_user(
        credentials: Annotated[HTTPAuthorizationCredentials, Depends(security)]
    ):
        return {"scheme": credentials.scheme, "credentials": credentials.credentials}
    ```
    """
    def __init__(self, *, scheme_name: Annotated[str | None, Doc("""
                Security scheme name.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., description: Annotated[str | None, Doc("""
                Security scheme description.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., auto_error: Annotated[bool, Doc("""
                By default, if the HTTP Digest is not provided, `HTTPDigest` will
                automatically cancel the request and send the client an error.

                If `auto_error` is set to `False`, when the HTTP Digest is not
                available, instead of erroring out, the dependency result will
                be `None`.

                This is useful when you want to have optional authentication.

                It is also useful when you want to have authentication that can be
                provided in one of multiple optional ways (for example, in HTTP
                Digest or in a cookie).
                """),] = ...) -> None:
        ...
    
    async def __call__(self, request: Request) -> HTTPAuthorizationCredentials | None:
        ...
    


