"""
This type stub file was generated by pyright.
"""

from typing import Annotated
from annotated_doc import Doc
from fastapi.security.base import SecurityBase
from starlette.exceptions import HTTPException
from starlette.requests import Request

class OpenIdConnect(SecurityBase):
    """
    OpenID Connect authentication class. An instance of it would be used as a
    dependency.

    **Warning**: this is only a stub to connect the components with OpenAPI in FastAPI,
    but it doesn't implement the full OpenIdConnect scheme, for example, it doesn't use
    the OpenIDConnect URL. You would need to subclass it and implement it in your
    code.
    """
    def __init__(self, *, openIdConnectUrl: Annotated[str, Doc("""
            The OpenID Connect URL.
            """),], scheme_name: Annotated[str | None, Doc("""
                Security scheme name.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., description: Annotated[str | None, Doc("""
                Security scheme description.

                It will be included in the generated OpenAPI (e.g. visible at `/docs`).
                """),] = ..., auto_error: Annotated[bool, Doc("""
                By default, if no HTTP Authorization header is provided, required for
                OpenID Connect authentication, it will automatically cancel the request
                and send the client an error.

                If `auto_error` is set to `False`, when the HTTP Authorization header
                is not available, instead of erroring out, the dependency result will
                be `None`.

                This is useful when you want to have optional authentication.

                It is also useful when you want to have authentication that can be
                provided in one of multiple optional ways (for example, with OpenID
                Connect or in a cookie).
                """),] = ...) -> None:
        ...
    
    def make_not_authenticated_error(self) -> HTTPException:
        ...
    
    async def __call__(self, request: Request) -> str | None:
        ...
    


